---
# https://github.com/repository-settings/app

repository:
  has_wiki: false

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# https://docs.github.com/en/rest/issues/labels
labels: []
